### ISSUE TITLE
Why my recordings can't be parsed?

### ISSUE THREAD

**Issue by Defozo** [happyleavesaoc/aoc-mgz#17] opened 2020-04-05 22:44 UTC
Some recordings downloaded from Voobly are working for me but unfortunately, some are not. Including my own.

This is what happens when I try to load my recording:
```
Traceback (most recent call last):
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 506, in _parse
    return packer.unpack(self.fmtstr, _read_stream(stream, self.sizeof()))[0]
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 69, in _read_stream
    raise FieldError("could not read enough bytes, expected %d, found %d" % (length, len(data)))
construct.core.FieldError: could not read enough bytes, expected 4, found 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 508, in _parse
    raise FieldError("packer %r error during parsing" % self.fmtstr)
construct.core.FieldError: packer '<f' error during parsing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1042, in _parse
    obj.append(self.subcon._parse(stream, context._, path))
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.FieldError: packer '<f' error during parsing
    (parsing) -> initial -> players -> objects -> objects -> properties -> building -> combat -> ai -> ai -> orders -> order -> target_location -> z

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1050, in _parse
    raise RangeError("expected %d to %d, found %d" % (min, max, len(obj)))
construct.core.RangeError: expected 4294918016 to 4294918016, found 35248

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1042, in _parse
    obj.append(self.subcon._parse(stream, context._, path))
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1594, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/mnt/c/aoe2/aoc-mgz/mgz/util.py", line 196, in _parse
    subobj = self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1594, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1594, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.RangeError: expected 4294918016 to 4294918016, found 35248
    (parsing) -> initial -> players -> objects -> objects -> properties -> building -> combat -> ai -> ai -> orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 1050, in _parse
    raise RangeError("expected %d to %d, found %d" % (min, max, len(obj)))
construct.core.RangeError: expected 6 to 6, found 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(header.parse_stream(data))
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/mnt/c/aoe2/aoc-mgz/mgz/util.py", line 54, in _parse
    return self.subcon._parse(new_stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 357, in _parse
    return self.subcon.parse(data, context)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/home/defozo/.local/lib/python3.7/site-packages/construct/core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.RangeError: expected 6 to 6, found 0
    (parsing) -> initial
```

We are using:
Game Mod: v1.5 RC | Allied Vision

You can download the recording here:
https://www.voobly.com/files/view/60445255/nfw5tdx83ea9eqmior7wkqsus9zo87ik

**Comment by happyleavesaoc** [comment] 2020-04-05 23:38
Can you provide the Voobly match link?

**Comment by Defozo** [comment] 2020-04-06 21:55
https://www.voobly.com/match/view/21570824

**Comment by happyleavesaoc** [comment] 2020-04-07 14:15
Hi, that match worked for me, what was the specific error you were getting, same as the previous?

**Comment by vinzeebreak** [comment] 2020-04-18 13:31
Hi, 

The match and recording provided by Defozo worked for me.  

However, the recording and match below give me a similar error to what Defozo experienced:
- matchid: [21711205](https://www.voobly.com/match/view/21711205)
- recording: https://voobly.com/files/view/60897356/ja9wxsh5cnwezf842b3c4tq3yr6ihivz

The code:

```python
with open(filename, 'rb') as data:
    eof = os.fstat(data.fileno()).st_size
    header.parse_stream(data)
    while data.tell() < eof:
        o = body.operation.parse_stream(data)
        print(o)
```

The error:

```
---------------------------------------------------------------------------
FieldError                                Traceback (most recent call last)
~/.virtualenvs/aoeii37/lib/python3.7/site-packages/construct/core.py in _parse(self, stream, context, path)
    505         try:
--> 506             return packer.unpack(self.fmtstr, _read_stream(stream, self.sizeof()))[0]
    507         except Exception:

~/.virtualenvs/aoeii37/lib/python3.7/site-packages/construct/core.py in _read_stream(stream, length)
     68     if len(data) != length:
---> 69         raise FieldError("could not read enough bytes, expected %d, found %d" % (length, len(data)))
     70     return data

FieldError: could not read enough bytes, expected 4, found 2

During handling of the above exception, another exception occurred:

FieldError                                Traceback (most recent call last)
~/.virtualenvs/aoeii37/lib/python3.7/site-packages/construct/core.py in _parse(self, stream, context, path)
   2783             path += " -> %s" % (self.name)
-> 2784             return self.subcon._parse(stream, context, path)
   2785         except ConstructError as e:

~/.virtualenvs/aoeii37/lib/python3.7/site-packages/construct/core.py in _parse(self, stream, context, path)
    507         except Exception:
--> 508             raise FieldError("packer %r error during parsing" % self.fmtstr)
    509     def _build(self, obj, stream, context, path):

FieldError: packer '<L' error during parsing
```

(I had to crop the error, since it was very long.)

**Comment by happyleavesaoc** [comment] 2020-04-18 18:20
Do you have the latest version checked out? (https://github.com/happyleavesaoc/aoc-mgz/commit/43ce8a42453c5b24e7867f635c748698f94962d9)

**Comment by vinzeebreak** [comment] 2020-04-19 09:55
Yes I do.

This is the content of my `pip freeze`:

```
aiohttp==3.6.2
astroid==2.3.3
async-timeout==3.0.1
attrs==19.3.0
backcall==0.1.0
beautifulsoup4==4.9.0
bleach==3.1.4
certifi==2020.4.5.1
chardet==3.0.4
construct==2.8.16
dateparser==0.7.4
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
flatbuffers==1.12
idna==2.9
importlib-metadata==1.6.0
ipykernel==5.2.1
ipython==7.13.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
-e git+git@github.com:vinzeebreak/aoc-mgz.git@43ce8a42453c5b24e7867f635c748698f94962d9#egg=mgz
mistune==0.8.4
multidict==4.7.5
nbconvert==5.6.1
nbformat==5.0.5
notebook==6.0.3
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
pipdeptree==0.13.2
prometheus-client==0.7.1
prompt-toolkit==3.0.5
ptyprocess==0.6.0
Pygments==2.6.1
pylint==2.4.4
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2019.3
pyzmq==19.0.0
qtconsole==4.7.3
QtPy==1.9.0
regex==2020.4.4
requests==2.23.0
Send2Trash==1.5.0
six==1.14.0
soupsieve==2.0
tablib==1.1.0
tabulate==0.8.7
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
typed-ast==1.4.1
tzlocal==2.0.0
urllib3==1.25.8
-e git+git@github.com:vinzeebreak/python-voobly.git@b0e68936a2f8f1b21686a36da3586dfb9bb4208f#egg=voobly
wcwidth==0.1.9
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.11.2
yarl==1.4.2
zipp==3.1.0
```

**Comment by happyleavesaoc** [comment] 2020-04-19 12:59
@vinzeebreak I very recently updated the `Parser` example in the README. There's now an extra requirement to read the `Meta` log data.

https://github.com/happyleavesaoc/aoc-mgz#parser

**Comment by happyleavesaoc** [comment] 2020-04-19 13:22
@vinzeebreak I also confirmed that the particular match you linked doesn't work. Will look into it, thanks for the report.

**Comment by happyleavesaoc** [comment] 2020-04-19 14:10
@vinzeebreak Fixed in https://github.com/happyleavesaoc/aoc-mgz/commit/e44f59930e4ee3787614548b727bfdc9c91c4390

The wonder object wasn't being parsed correctly.

**Comment by vinzeebreak** [comment] 2020-04-20 20:19
I confirm that it works now. Thank you!

**Comment by happyleavesaoc** [comment] 2020-05-06 18:48
Closing this as I haven't heard from @Defozo for awhile. Feel free to re-open if your issue persists.

**Closed by happyleavesaoc** 2020-05-06 18:48 UTC
